version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: /usr/src/app
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Disable yarn progress bar for perf
      - run:
          command: yarn config set no-progress

      # Greenkeeper-lockfile
      - run:
          name: Installing Greenkeeper-lockfile
          command: yarn global add greenkeeper-lockfile@1

      # Install dependencies
      - run:
          name: Installing Dependencies
          command: yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Update yarn.lock
      - run:
          name: Updating lockfile
          command: greenkeeper-lockfile-update

      # Test
      - run:
          name: Tests
          command: yarn test

      # Build
      - run:
          name: Building nuxt site
          command: yarn generate

      # Upload yarn.lock
      - run:
          name: Uploading lockfile
          command: greenkeeper-lockfile-upload

      - persist_to_workspace:
          root: /usr/src/app
          paths:
            - dist/*
            - .circleci/*
